### ISSUE TITLE
Add grapetree link in front end and pipe api into the link

### ISSUE THREAD

**Issue by Fattigman** [Fattigman/docker-sc2reporter#104]
Add links in the front end as described in #91

**Comment by Fattigman** [comment]
Grapetree can be found on https://34.125.210.143/grapetree/

**Comment by moedarrah** [comment]
The link is not working @Fattigman

**Comment by Fattigman** [comment]
We changed it in #119 
https://34.125.84.98/grapetree/

**Comment by moedarrah** [comment]
Done: https://github.com/genomic-medicine-sweden/docker-sc2reporter/pull/130
