### ISSUE TITLE
Remove trailing slashes from front end requests

### ISSUE THREAD

**Issue by Fattigman** [Fattigman/docker-sc2reporter#117]
When doing calls to the backend, refrain from ending your call with trailing slashes. 

FastAPI has a weird behaviour that it tries to redirect when it find trailing slashes.
I tried to fix it with #101 but it just introduced new bugs #110 and #109. 

So I will do rollback and in the end you shouldnt end your calls with trailing slashes.

**Comment by Fattigman** [comment]
I was wrong, it should end with trailing slashes

**Comment by moedarrah** [comment]
Done!
