### ISSUE TITLE
Variant view

### ISSUE THREAD

**Issue by moedarrah** [Fattigman/docker-sc2reporter#122]
What to show in the Variant View

**Comment by Fattigman** [comment]
Here is an image on what to show from the flask version:
<img width="798" alt="Screenshot 2023-02-22 at 10 21 11" src="https://user-images.githubusercontent.com/32386766/220577277-989c8812-bf31-4df6-9058-e934f1ac66ea.png">

**Comment by moedarrah** [comment]
The variant endpoint is not working

**Comment by talnor** [comment]
This is the same issue as https://github.com/genomic-medicine-sweden/docker-sc2reporter/issues/29?

**Comment by Fattigman** [comment]
It is indeed, I will close it then because of duplication

**Comment by Fattigman** [comment]
We need to clarify 
* cDNA Change
* Codon change
* Protein change
* External link CoVariants

**Comment by Fattigman** [comment]
Codon change = Codons
cDNA change = HGVSc
Protein change = HGVSp

**Comment by Fattigman** [comment]
The last one is a bit more tricky. It looks like:
External link CoVariant = https://covariants.org/variants/{ SYMBOL+':'+HGVSp}
But it's constructed like:

It is parsed in the code like:
```python
https://covariants.org/variants/{ covariants[v] }

covariants = {
        "S:A222V": "20A.EU1", "S:S477N": "20A.EU2", "S:N501Y": "S.N501", "S:E484K": "S.E484",
        "S:H69_V70del": "S.H69-", "S:N439K": "S.N439K", "S:Y453F": "S.Y453F", "S:S98F": "S.S98F",
        "S:L452R": "S.L452R", "S:D80Y": "S.D80Y", "S:A626S": "S.A626S", "S:V1122L": "S.V1122L",
        "S:Q677H": "S.Q677"
    }
var_show = v
if v == "S:H69_V70del":
        var_show = "S.H69-"
```
Here is the web site it uses https://covariants.org/variants if you want to investigate the how the urls are constructed.
Maybe this should be done in the backend instead?

**Comment by moedarrah** [comment]
I agree it would be better to send it from the backend.

**Comment by Fattigman** [comment]
This is now done via backend at #162
