### ISSUE TITLE
Remove old frontend from add-react-app

### ISSUE THREAD

**Issue by moedarrah** [Fattigman/docker-sc2reporter#60]
Since we are going to use the add-react-app branch as our main development branch (backend, frontend) we can do some code cleaning and remove the old python frontend.

**Comment by Fattigman** [comment]
Renamed the old "main" branch to "flask-app" and changed the main branch to "add-react-app" which contains both front-end and back-end. 

Was this the intended outcome of the issue?

**Comment by moedarrah** [comment]
No need to rename any branch, I think the best way is to clean the add-react-app branch from all the unused code from V1.

**Comment by Fattigman** [comment]
Ok, I cleaned it and published it as the branch remove-v1.
