### ISSUE TITLE
Dashboard - Pango observations per week

### ISSUE THREAD

**Issue by moedarrah** [Fattigman/docker-sc2reporter#75]
<img width="223" alt="Screenshot 2022-11-02 at 10 44 12" src="https://user-images.githubusercontent.com/41540288/199457137-fcf8c9b5-533f-4ce0-abc8-570070dbb8e4.png">

**Comment by Fattigman** [comment]
We will change this feature from per week, to per date. 
Also, the table will not be displayed and will be replaced by a download button. 
Is this an appropriate change @LordRust

**Comment by moedarrah** [comment]
After discussing the issue with @LordRust, we will not show the table instead we will have only the download button with two options: per week, and per date. Also, we will have the year next to week number
