### ISSUE TITLE
Add url prefix to react frontend

### ISSUE THREAD

**Issue by Fattigman** [Fattigman/docker-sc2reporter#92]
The base path of the URL should be easily modifiable, in order to host the application on a local server with several applications already hosted there. Otherwise, the application's HTTP responses to the server will route to the wrong URLs.

Like so:
```bash 
localhost:3000/<ROOT_PATH>
```
One way to do it would be to add an environment variable to the docker-compose.yml file. 
This environment variable is then used in the frontend application to set the prefix at the application level.

This issue can be closed when:

- [ ] The front-end URL can easily be prefixed.

**Comment by moedarrah** [comment]
https://github.com/genomic-medicine-sweden/docker-sc2reporter/pull/108

**Comment by moedarrah** [comment]
Done!
